### ISSUE TITLE
Incompatible with the current Intellij IDEA version

### ISSUE THREAD

**Issue by landsman** [tomas-milata/intelliroutes#7]
version: `2019.2` Ultimate Edition
updated by Snap

**Comment by tomas-milata** [comment]
Thanks for reporting. I don't have a stable version for 2019.2 because it's still an EAP version, but in the meantime, you might try using a version of this plugin from the alpha channel. You need to add `https://plugins.jetbrains.com/plugins/alpha/10053` as your custom plugin repository channel.

BTW, I'm surprised you're using my plugin instead of the JetBrains' one. (I believe the Scala plugin by JetBrains has Play/routes support in IJ Ultimate -- I created my plugin as a free alternative). Have you tried that one?

**Comment by landsman** [comment]
@tomas-milata actually I did downgrade because there was more unstable plugins. I already have installed Scala plugin but there is no feature about routes as you have.
